version: "3.8"

services:
  db:
    container_name: postgres-db
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  broker:
    container_name: redis-broker
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  pdf-printer:
    container_name: wkhtmltopdf
    image: openlabs/docker-wkhtmltopdf-aas
    restart: unless-stopped
    ports:
      - "8989:80"

volumes:
  data:
    name: check-data
