# Generated by Django 4.2.3 on 2023-07-18 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('check_type', models.CharField(choices=[('CLT', 'Client'), ('KIT', 'Kitchen')], max_length=3)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLT', 'Client'), ('KIT', 'Kitchen')], max_length=3)),
                ('order', models.JSONField(blank=True)),
                ('status', models.CharField(choices=[('N', 'new'), ('R', 'ready'), ('P', 'printed')], default='N', max_length=1)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.printer')),
            ],
        ),
    ]
